### ISSUE TITLE
Add engines to package.json

### ISSUE THREAD

**Issue by gustavoschmidt** [gustavoschmidt/cuppy#5]
Decide between yarn and npm (read about pros and cons). Then add to package.json:

```
"engines": {
    "node": "8.7.0",
    "yarn": "1.3.2"
  },
```

or 

```
"engines": {
    "node": "8.7.0",
    "npm": "5.4.2"
  },
```

Make sure your node version is up to date.

**Comment by barbalatr** [comment]
Couldn't check node version with yarn.
Tried npm install check-node-version but it created a file named package-lock.json
